$(document).ready(function(){
    $("#jerk").click(function(){
        $('#logan').hide("slow");
        $("#loginan").toggle("slow");
    });
    $("#jerk2").click(function(){
        $("#logan").toggle("slow");
        $('#loginan').hide("slow");
    });
    $("#dsbrd").click(function(){
        $('.kotak1').toggle("slow");
        $('.kotak2').toggle("slow");
        $('.kotak3').toggle("slow");
        $('.kotak4').toggle("slow");
    	$('#tabel_anggota').hide("slow");
        $('#tabel_pinjam').hide("slow");
        $('#tabel_pinjamm').hide("slow");
        $('#tabel_simpanan').hide("slow");
    });
    $("#datamember").click(function(){
        $('#tabel_anggota').toggle("slow");
        $('#tabel_pinjam').hide("slow");
        $('.kotak1').hide("slow");
        $('.kotak2').hide("slow");
        $('.kotak3').hide("slow");
        $('.kotak4').hide("slow");
        $('#tabel_pinjamm').hide("slow");
        $('#tabel_simpanan').hide("slow");
    });
    $("#pinjam").click(function(){
        $('#tabel_pinjam').toggle("slow");
        $('#tabel_anggota').hide("slow");
        $('.kotak1').hide("slow");
        $('.kotak2').hide("slow");
        $('.kotak3').hide("slow");
        $('.kotak4').hide("slow");
        $('#tabel_pinjamm').hide("slow");
        $('#tabel_simpanan').hide("slow");
    });
     $("#angsuran").click(function(){
        $('#tabel_pinjamm').toggle("slow");
        $('#tabel_pinjam').hide("slow");
        $('#tabel_anggota').hide("slow");
        $('.kotak1').hide("slow");
        $('.kotak2').hide("slow");
        $('.kotak3').hide("slow");
        $('.kotak4').hide("slow");
         $('#tabel_simpanan').hide("slow");
    });
     $("#simpan").click(function(){
        $('#tabel_simpanan').toggle("slow");
        $('#tabel_pinjamm').hide("slow");
        $('#tabel_pinjam').hide("slow");
        $('#tabel_anggota').hide("slow");
        $('.kotak1').hide("slow");
        $('.kotak2').hide("slow");
        $('.kotak3').hide("slow");
        $('.kotak4').hide("slow");
    });
});
