$(document).ready(function(){
	$("#user").click(function(){
		$("#rsimpan").hide("slow");
		$("#rpinjam").hide("slow");
		$("#rangsuran").hide("slow");
		$("#simpan").hide("slow");
		$("#pinjam").hide("slow");
		$("#angsuran").hide("slow");
		$("#datauser").toggle("slow");
		$("#datamember").toggle("slow");
	});
	$("#transaksi").click(function(){
		$("#rsimpan").hide("slow");
		$("#rpinjam").hide("slow");
		$("#rangsuran").hide("slow");
		$("#datauser").hide("slow");
		$("#datamember").hide("slow");
		$("#simpan").toggle("slow");
		$("#pinjam").toggle("slow");
		$("#angsuran").toggle("slow");
	});
	$("#report").click(function(){
		$("#datauser").hide("slow");
		$("#datamember").hide("slow");
		$("#simpan").hide("slow");
		$("#pinjam").hide("slow");
		$("#angsuran").hide("slow");
		$("#rsimpan").toggle("slow");
		$("#rpinjam").toggle("slow");
		$("#rangsuran").toggle("slow");
	});
});